# KOHONEN
ALPHA_KOHONEN = 0.01
EPOCHS_KOHONEN = 100
KOHONEN_LAYER_COUNT = 3
NORMALIZE_PARAMETER = 3
HIDDEN_LAYER_COUNT = 8

# MLP
RANDOM_SEED = 163
NN_LAYERS = [13, HIDDEN_LAYER_COUNT, KOHONEN_LAYER_COUNT]  # Топология нейронной сети
LEARN_PERCENTAGE = 0.6

EPOCHS = 100
LEARNING_RATE = 0.5
# ALPHA = 0.9

# Optimal parameters
ALPHA = 0.15

